# fly.toml app configuration file generated for todopad on 2024-12-30T15:38:43+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todopad'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "todopad"
  destination = "/data"
